### ISSUE TITLE
Shortterm to do.

### ISSUE THREAD

**Issue by spijs** [spijs/thesisImageNL#1]
## Todo Wout
- [x] Die code duplicatie fixen zodat die files naar juiste naam worden uitgeschreven bij lda
- [x] LDA  terug runnen op paris voor 120 topics e.a. als bovenstaande is gefixt.
- [x] Error fixen in dataprovider
